name: Build

on: [push, pull_request]

jobs:
  Windows-VC:
    runs-on: windows-2022
    timeout-minutes: 10
    steps:
      - name: "Checkout"
        with: 
            repository: 'mruby/mruby'
            ref: '3.3.0'
        uses: actions/checkout@v4
      - name: Ruby version
        run: ruby -v
      - uses: suisei-cn/actions-download-file@818d6b7dc8fe73f2f924b6241f2b1134ca1377d9 # 1.6.0
        name: Download the file
        with:
          url: "https://raw.githubusercontent.com/zekexiao/mruby-build/refs/heads/master/msvc.rb"
          target: ./
      - name: Build and test
        shell: cmd
        run: |
          call "C:\Program Files\Microsoft Visual Studio\2022\Enterprise\VC\Auxiliary\Build\vcvars64.bat"
          rake MRUBY_CONFIG=msvc.rb
      - name: Upload
        with:
          path: build/host
        uses: actions/upload-artifact@v4
